openapi: 3.0.0
info:
  version: 0.0.1
  title: CrashTeam Uzum Analytics API
  description:
    $ref: './docs/api.md'
  termsOfService: http://marketdb.ru/terms-of-use/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://{subdomain}.marketdb.org/{version}'
    variables:
      subdomain:
        default: api
      version:
        enum:
          - v2
        default: v2
security:
  - apiKey: []
paths:
  '/seller/link':
    $ref: './paths/sellers.yaml'
  '/product/{productId}/sku/{skuId}/sales':
    $ref: './paths/product@{productId}sku@{skuId}sales.yaml'
  '/product/sales':
    $ref: './paths/product-sales.yaml'
  '/category/{categoryId}/overall-info':
    $ref: './paths/category@{categoryId}overall-info.yaml'
  '/seller/{sellerLink}/overall-info':
    $ref: './paths/seller@{sellerLink}overall-info.yaml'
components:
  securitySchemes:
    apiKey:
      $ref: './components/security-schemes/ApiKey.yaml'
